var GKUtils={ANIM_DURATION:1E3,getData:function(d){return d&&d.values&&d.values.length?d.values:null},extend:function(d,f){for(var h in f)f.hasOwnProperty(h)&&(d[h]=f[h]);return d},fadeIn:function(d){d.css("display","block");setTimeout(function(){d.css("opacity","1")},50)},fadeOut:function(d,f){f=f||500;d.css("opacity","0");setTimeout(function(){d.hide()},f)},animate:function(d,f,h){d.css(f);h&&setTimeout(h,this.ANIM_DURATION)}};
if(Array&&Array.prototype&&"undefined"===typeof Array.prototype.forEach)Array.prototype.forEach=function(d){var f;for(f=0;void 0>f;++f)d(this[f])};if(Object&&"undefined"===typeof Object.keys)Object.keys=function(d){var f=0,h;for(h in d)d.hasOwnProperty(h)&&++f};
if(Function&&Function.prototype&&!Function.prototype.bind)Function.prototype.bind=function(d){if("function"!==typeof this)throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");var f=Array.prototype.slice.call(arguments,1),h=this,o=function(){},p=function(){return h.apply(this instanceof o?this:d||window,f.concat(Array.prototype.slice.call(arguments)))};o.prototype=this.prototype;p.prototype=new o;return p};var NetworkGraph;
(function(){var d=$(window);$("#viewport");var f=$("#companyTitle"),h=GKUtils.ANIM_DURATION||1E3,o={},p=[],k=!1,m=!1,n,u,v,x,q,r,s,l,w;l={isInBounds:function(a,b,c){return this.xInBounds(a,c)&&this.yInBounds(b,c)},xInBounds:function(a,b){return 0<a-b&&890>a+b},yInBounds:function(a,b){return 0<a-b&&a+b<(k?200:660)},getRandomCenter:function(a){var b=Math.floor(890*Math.random()),c=Math.floor(Math.random()*(k?200:660));return l.moveAwayFromEdge(b,c,a)},isIntersecting:function(a,b){var c=a.r,e=b.r,j=
2*c,d=2*e,g=a.cx-c,f=b.cx-e,c=a.cy-c,e=b.cy-e;return g+j>=f&&g<=f+d&&c+j>=e&&c<=e+d},moveAwayFromEdge:function(a,b,c){var e=k?200:660;0>=a-c?a=c:890<a+c&&(a=890-c);0>=b-c?b=c:b+c>e&&(b=e-c);return{x:a,y:b}}};q=function(){};q.prototype={createEl:function(a,b,c,e){this.r=b;this.$circle=$("<div>").addClass("circle "+e+"-circ").css({width:2*b,height:2*b});this.setBorderRadius(b);this.$label=$("<span>").addClass(e+"-label").css({top:b-8+"px",left:b-100+"px"}).text(c);this.$circle.append(this.$label);this.$container=
$("<div>").addClass("circle-container "+e+"-circ-container").attr("id","circle-"+a).append(this.$circle);return this},setBorderRadius:function(a){a*=2;this.$circle.css({"-moz-border-radius":a+"px","-ms-border-radius":a+"px","-o-border-radius":a+"px","-webkit-border-radius":a+"px","border-radius":a+"px"})},show:function(){this.$container.show();return this},hide:function(){this.$container.hide();return this},move:function(a,b,c){var e={left:a-this.r,top:b-this.r};this.cx=a;this.cy=b;GKUtils.animate(this.$container,
e,c);return this},setRadius:function(a,b,c){var e=2*a;"undefined"===typeof b&&(b=!0);"undefined"===typeof c&&(c=!0);b&&this.$container.css({left:this.cx-a,top:this.cy-a});this.$circle.css({width:e+"px",height:e+"px"});c&&40<=a?this.$label.show():this.$label.hide();this.r=a;this.setBorderRadius(a);return this},setElPosition:function(a,b,c){this.cx=a;this.cy=b;this.$container.css({left:this.cx-c,top:this.cy-c});return this},findOpenSpace:function(a,b,c){var e=Math.PI,j=this.cx-a,d=b-this.cy,g=Math.sqrt(j*
j+d*d),g=Math.asin(d/g),c=Math.max(3*c/2,30)+this.r,f=[e/6,e/4,e/3,e/2,2*e/3,3*e/4,5*e/6,e],i;0>j&&0<d?g=e-g:0>g&&0>j&&0>d?g=e-g:this.cy===b&&0>j&&(g=e);e=a+Math.cos(g)*c;i=b+-1*Math.sin(g)*c;for(j=0,d=f.length;j<d&&!l.isInBounds(e,i,this.r);++j){i=g+f[j++];e=a+Math.cos(i)*c;i=b+-1*Math.sin(i)*c;if(l.isInBounds(e,i,this.r))break;i=g-f[j++];e=a+Math.cos(i)*c;i=b+-1*Math.sin(i)*c}if(!l.isInBounds(e,i,this.r))console.log("Couldn't find a in-bounds position to jump to!"),a=l.getRandomCenter(this.r),e=
a.x,i=a.y;this.move(e,i)},moveOverlapCirclesProto:function(a){var b=this,c=[];a.forEach(function(a){a!==b&&l.isIntersecting(b,a)&&c.push(a)});c.forEach(function(a){a.findOpenSpace(b.cx,b.cy,b.r)})},getContainer:function(){return this.$container}};x=function(){var a,b,c,e=function(){percent=c/910;d.trigger("sliderStop",percent);b&&(window.clearTimeout(b),b=null)},j=function(){b&&window.clearTimeout(b);b=setTimeout(e,100)},f=function(a){c=a;b||(b=setTimeout(e,250))},g=function(a,b){d.trigger("sliderStart");
k&&n&&(k=!1,n.unhighlight(),m=!0,d.trigger("unhighlight"));c=b.position.left;j()},h=function(a,b){percent=c/910;d.trigger("sliderDrag",percent);c=b.position.left;j()},i=function(){b&&(window.clearTimeout(b),b=null,e())},t=function(){var b=this.$el.width()-40,c=a.position().left,e=12E3*((b-c)/b);c>=b&&a.css("left",0);a.animate({left:b},{easing:"linear",duration:e,step:f})};(function(){this.$el=$("#slider");this.$playBtn=$("#playBtn").click(t.bind(this));a=this.$el.find("#sliderHandle");a.draggable({axis:"x",
containment:"parent",start:g,drag:h,stop:i})})()};r=function(a){this.init(a)};r.prototype=new q;GKUtils.extend(r.prototype,{show:function(){var a=this;this.$container.show();setTimeout(function(){a.$container.css("top",a.top)},50)},hide:function(){var a=this;GKUtils.animate(this.$container,{top:460},function(){a.$container.hide()})},setCenter:function(a,b){var c=this.IMG_DIM;this.el.attr({x:a-c/2,y:b-c/2})},setImageWidth:function(a){this.$container.find("img").css({width:a,height:a});return this},
prepareElPosition:function(){var a=2*this.r;this.top=this.rowNum*a;this.left=this.colNum*a;this.setElPosition(this.left+this.r,460+this.r,this.r)},init:function(a){l.getRandomCenter(40);var b=$("<a>"),c=a.pictureUrl||"img/icon_no_photo_80x80.png",e=a.siteStandardProfileRequest?a.siteStandardProfileRequest.url:"#",d=Math.random()/2+0.5+"s";this.id=a.id;this.profile=a;this.createEl(a.id,40,a.firstName+" "+a.lastName,"cxn");this.$container.css({"-moz-transition-duration":d,"-ms-transition-duration":d,
"-o-transition-duration":d,"-webkit-transition-duration":d,"transition-duration":d});b.attr({href:e||"#",title:a.firstName+" "+a.lastName,target:"_new"});b.append($("<img>").addClass("cxn-picture").attr("src",c));this.$circle.append(b)}});s=function(a,b,c,e){this.init(a,b,c,e)};s.prototype=new q;GKUtils.extend(s.prototype,{calculateCmpyRadius:function(a){return Math.max(100-1E3/(a+10),10)},moveOverlapCircles:function(){return this.moveOverlapCirclesProto.call(this,p)},setEmployees:function(a){var b=
this.calculateCmpyRadius(a.length),c=this.cx,e=this.cy;this.employees=a;if(!l.isInBounds(c,e,b))a=l.moveAwayFromEdge(c,e,b),c=a.x,e=a.y,this.move(c,e);this.r!==b&&(this.setRadius(b),this.$label.css({top:b-8+"px",left:b-100+"px"}));return this},resetLabelPosition:function(){var a=this.el;this.label.attr({x:a.attr("cx"),y:a.attr("cy")-a.attr("r")-5})},doHoverIn:function(){m||(this.$container.addClass("hover"),this.$label.show(),this.moveOverlapCircles())},doHoverOut:function(){this.$container.removeClass("hover");
40>this.r&&this.$label.hide()},doClick:function(){!this.wasDragging&&!m&&((k=!k)?(this.highlight(),n=this,m=!0,d.trigger("highlight",{employees:this.employees})):(m=!0,n.unhighlight(),this==n?d.trigger("unhighlight"):(k=!0,this.highlight(),n=this,d.trigger("replaceEmployees",{employees:this.employees}))));this.wasDragging=!1},doDragStop:function(a,b){this.wasDragging=!0;this.cx=b.position.left+this.r;this.cy=b.position.top+this.r;this.moveOverlapCircles()},highlight:function(){var a=this;this.$label.show();
window.setTimeout(function(){a.$container.addClass("highlighted")},h)},unhighlight:function(){this.$container.removeClass("highlighted");GKUtils.fadeOut(f,h)},init:function(a,b,c,e){var d=this.calculateCmpyRadius(b.length),f=l.getRandomCenter(d),g=f.x,f=f.y;this.id=a;this.origR=d;this.name=c;this.createEl(this.id,d,c,"cmpy").setElPosition(g,f,d);this.$circle.click(this.doClick.bind(this)).hover(this.doHoverIn.bind(this),this.doHoverOut.bind(this));this.$container.addClass(e?"school":"").css("position",
"absolute").draggable({containment:"parent",stop:this.doDragStop.bind(this)});40<=d&&this.$label.show();this.employees=b;this.pictures=[]}});w=function(){this.init()};w.prototype={$viewport:$("#companies"),add:function(a,b,c,e){a=new s(a,b,c,e);this.renderCompany(a);return a},renderCompany:function(a){this.$viewport.append(a.getContainer())},showRemainingCompanies:function(a,b,c){var e,d;for(d in a)if(e=a[d])(cmpyCircle=o[d])?cmpyCircle.setEmployees(e).show():(cmpyCircle=this.add(d,a[d],v[d],b),o[d]=
cmpyCircle),c.push(cmpyCircle)},renderCompanies:function(a,b){var c;m?this.cmpysToRender={companies:a,schools:b}:(c=[],p.forEach(function(e){var d=a[e.id],f=b[e.id];d?(e.setEmployees(d),c.push(e),a[e.id]=null):f?(e.setEmployees(f),c.push(e),b[e.id]=null):e.hide()}),this.showRemainingCompanies(a,!1,c),this.showRemainingCompanies(b,!0,c),p=c)},resizeArea:function(){var a=k?200:660,b;k||(b=function(){m=!1;d.trigger("animComplete")});GKUtils.animate(this.$viewport,{height:a+"px"},b);p.forEach(function(a){var b,
d;k?(a.origCx=a.cx,a.origCy=a.cy,b=a.cy-a.r,d=a.cx,b=200*(b/660)+a.r,200<=b+a.r&&(b=200-a.r)):(d=a.origCx,b=a.origCy);a.setElPosition(d,b,a.r)})},init:function(){var a=this;this.$el=$("#companies");d.on("highlight",this.resizeArea.bind(this));d.on("unhighlight",this.resizeArea.bind(this));d.on("animComplete",function(){if(a.cmpysToRender)a.renderCompanies(a.cmpysToRender.companies,a.cmpysToRender.schools),a.cmpysToRender=null})}};ConnectionView=function(){this.init()};ConnectionView.prototype={pictureWidth:80,
circles:{},currCxns:[],loadEmployees:function(a,b){var c=b.employees,e=c.length,d,f,g,h,i,t,y;63.96875<e?(this.pictureWidth=Math.floor(9*Math.sqrt(409400/e)/10),this.pictureWidth=Math.max(30,this.pictureWidth)):this.pictureWidth=80;t=Math.floor(890/this.pictureWidth);y=(c.length-1)/t+1;for(e=0,d=c.length;e<d;++e)f=c[e],f=u[f],g=this.circles[f.id],h=Math.floor(e/t),i=e%t,g||(g=new r(f),this.circles[f.id]=g,this.$el.append(g.getContainer())),g.rowNum=h,g.colNum=i,g.setRadius(this.pictureWidth/2,!1,
!1).setImageWidth(this.pictureWidth).prepareElPosition(t,y),this.currCxns.push(g);this.showEmployees();return this},showEmployees:function(){var a=this;this.$wrapper.addClass("show");setTimeout(function(){a.currCxns.forEach(function(a){a.show()})},50);setTimeout(function(){m=!1;d.trigger("animComplete")},h)},replaceEmployees:function(a,b){var c=this;this.hideEmployees(null,function(){c.loadEmployees(null,b).showEmployees()})},hideEmployees:function(a,b){var c=this;this.currCxns.forEach(function(a){a.hide()});
this.currCxns=[];setTimeout(function(){c.$wrapper.removeClass("show");b&&b()},h)},init:function(){this.$el=$("#connections");this.$wrapper=$("#connections-wrapper");d.on("highlight",this.loadEmployees.bind(this));d.on("replaceEmployees",this.replaceEmployees.bind(this));d.on("unhighlight",this.hideEmployees.bind(this))}};NetworkGraph=function(){this.init()};NetworkGraph.prototype={setCompanies:function(a,b){this.cmpyCollection.renderCompanies(a,b)},setData:function(a){u=a.profiles||null;v=a.cmpyNames||
null},init:function(){this.sliderBar=new x;this.cmpyCollection=new w;this.cxnView=new ConnectionView}}})();var onLinkedInLoad;
$(function(){var d,f,h,o=new NetworkGraph,p=(new Date).getTime(),k=$("#date"),m=$("#signin"),n,u,v,x,q,r,s,l="Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec".split(","),w=function(a){a=new Date(a);a.setDate(15);a.setHours(0);a.setMinutes(0);a.setSeconds(0);a.setMilliseconds(0);return a},a=function(a,b){var c;n&&u&&(c=w(q+r*b),s.postMessage({allCmpyEmployees:n,allSchoolmates:u,targetDate:c.getTime()}))},b=function(a,b){var c,d;c=w(q+r*b);d=l[c.getMonth()];c=c.getFullYear();k.text(d+" "+c)},c=function(){var a=
GKUtils.getData(d),b=GKUtils.getData(f);if(!b||!a)throw"No profile data";b.push(a);h=b;a=new Worker("js/cxnWorker.js");a.addEventListener("message",function(a){if(a.data)n=a.data.companies,u=a.data.schools,v=a.data.cmpyNames,x=a.data.profileObjs,q=a.data.earliestDate,r=p-q,o.setData({profiles:x,cmpyNames:v}),GKUtils.fadeIn($("#intro2, #slider, #share"))},!1);a.postMessage({profiles:h})},e=function(a){$("#yourname").text(a.firstName);setTimeout(function(){GKUtils.fadeIn($("#intro1"))},500)},j=function(a){var b=
GKUtils.getData(a);if(b&&b.length)e(b[0]);else throw"Couldn't find your profile!";d=a;f&&c()},z=function(a){f=a;d&&c()},g=function(a){var b;a.data&&(b=a.data.currCompanies||null,currSchools=a.data.currSchools||null);b&&o.setCompanies(b,currSchools,v)},A=function(){var a="id first-name last-name positions:(start-date,end-date,company:(id,name)) picture-url educations:(school-name,start-date,end-date) site-standard-profile-request:(url)".split(" ");GKUtils.fadeOut(m,500);setTimeout(function(){GKUtils.fadeIn($("#companies"))},
500);$("#viewport").show();IN.API.Profile("me").fields(a).result(j);IN.API.Connections("me").fields(a).result(z)};onLinkedInLoad=function(){GKUtils.fadeIn($("#signin, #title"));IN.Event.on(IN,"auth",A)};(function(){$(window).bind("sliderStop",a);$(window).bind("sliderDrag",b);$(window).bind("sliderStart",function(){GKUtils.fadeOut($(".intro"),500)});s=new Worker("js/snapshotWorker.js");s.addEventListener("message",g,!1)})()});
