var GKUtils={ANIM_DURATION:1E3,getData:function(c){return c&&c.values&&c.values.length?c.values:null},extend:function(c,f){for(var h in f)f.hasOwnProperty(h)&&(c[h]=f[h]);return c},fadeIn:function(c){c.css("display","block");setTimeout(function(){c.css("opacity","1")},50)},fadeOut:function(c,f){f=f||500;c.css("opacity","0");setTimeout(function(){c.hide()},f)},animate:function(c,f,h){c.css(f);h&&setTimeout(h,this.ANIM_DURATION)}};
if(Array&&Array.prototype&&"undefined"===typeof Array.prototype.forEach)Array.prototype.forEach=function(c){var f;for(f=0;void 0>f;++f)c(this[f])};if(Object&&"undefined"===typeof Object.keys)Object.keys=function(c){var f=0,h;for(h in c)c.hasOwnProperty(h)&&++f};
if(Function&&Function.prototype&&!Function.prototype.bind)Function.prototype.bind=function(c){if("function"!==typeof this)throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");var f=Array.prototype.slice.call(arguments,1),h=this,o=function(){},p=function(){return h.apply(this instanceof o?this:c||window,f.concat(Array.prototype.slice.call(arguments)))};o.prototype=this.prototype;p.prototype=new o;return p};var NetworkGraph;
(function(){var c=$(window);$("#viewport");var f=$("#companyTitle"),h=GKUtils.ANIM_DURATION||1E3,o={},p=[],l=!1,m=!1,n,t,u,v,q,s,r,k,w;k={isInBounds:function(a,b,d){return this.xInBounds(a,d)&&this.yInBounds(b,d)},xInBounds:function(a,b){return 0<a-b&&890>a+b},yInBounds:function(a,b){return 0<a-b&&a+b<(l?200:660)},getRandomCenter:function(a){var b=Math.floor(890*Math.random()),d=Math.floor(Math.random()*(l?200:660));return k.moveAwayFromEdge(b,d,a)},isIntersecting:function(a,b){var d=a.r,e=b.r,j=
2*d,c=2*e,g=a.cx-d,f=b.cx-e,d=a.cy-d,e=b.cy-e;return g+j>=f&&g<=f+c&&d+j>=e&&d<=e+c},moveAwayFromEdge:function(a,b,d){var e=l?200:660;0>=a-d?a=d:890<a+d&&(a=890-d);0>=b-d?b=d:b+d>e&&(b=e-d);return{x:a,y:b}}};q=function(){};q.prototype={createEl:function(a,b,d,e){this.r=b;this.$circle=$("<div>").addClass("circle "+e+"-circ").css({width:2*b,height:2*b});this.setBorderRadius(b);this.$label=$("<span>").addClass(e+"-label").css({top:b-8+"px",left:b-100+"px"}).text(d);this.$circle.append(this.$label);this.$container=
$("<div>").addClass("circle-container "+e+"-circ-container").attr("id","circle-"+a).append(this.$circle);return this},setBorderRadius:function(a){a*=2;this.$circle.css({"-moz-border-radius":a+"px","-ms-border-radius":a+"px","-o-border-radius":a+"px","-webkit-border-radius":a+"px","border-radius":a+"px"})},show:function(){this.$container.show();return this},hide:function(){this.$container.hide();return this},move:function(a,b,d){var e={left:a-this.r,top:b-this.r};this.cx=a;this.cy=b;GKUtils.animate(this.$container,
e,d);return this},setRadius:function(a,b,d){var e=2*a;"undefined"===typeof b&&(b=!0);"undefined"===typeof d&&(d=!0);b&&this.$container.css({left:this.cx-a,top:this.cy-a});this.$circle.css({width:e+"px",height:e+"px"});d&&40<=a?this.$label.show():this.$label.hide();this.r=a;this.setBorderRadius(a);return this},setElPosition:function(a,b,d){this.cx=a;this.cy=b;this.$container.css({left:this.cx-d,top:this.cy-d});return this},findOpenSpace:function(a,b,d){var e=Math.PI,j=this.cx-a,c=b-this.cy,g=Math.sqrt(j*
j+c*c),g=Math.asin(c/g),d=Math.max(3*d/2,30)+this.r,f=[e/6,e/4,e/3,e/2,2*e/3,3*e/4,5*e/6,e],i;0>j&&0<c?g=e-g:0>g&&0>j&&0>c?g=e-g:this.cy===b&&0>j&&(g=e);e=a+Math.cos(g)*d;i=b+-1*Math.sin(g)*d;for(j=0,c=f.length;j<c&&!k.isInBounds(e,i,this.r);++j){i=g+f[j++];e=a+Math.cos(i)*d;i=b+-1*Math.sin(i)*d;if(k.isInBounds(e,i,this.r))break;i=g-f[j++];e=a+Math.cos(i)*d;i=b+-1*Math.sin(i)*d}if(!k.isInBounds(e,i,this.r))console.log("Couldn't find a in-bounds position to jump to!"),a=k.getRandomCenter(this.r),e=
a.x,i=a.y;this.move(e,i)},moveOverlapCirclesProto:function(a){var b=this,d=[];a.forEach(function(a){a!==b&&k.isIntersecting(b,a)&&d.push(a)});d.forEach(function(a){a.findOpenSpace(b.cx,b.cy,b.r)})},getContainer:function(){return this.$container}};v=function(){var a,b,d,e=function(){percent=d/910;c.trigger("sliderStop",percent);b&&(window.clearTimeout(b),b=null)},j=function(){b&&window.clearTimeout(b);b=setTimeout(e,100)},f=function(a,b){c.trigger("sliderStart");l&&n&&(l=!1,n.unhighlight(),m=!0,c.trigger("unhighlight"));
d=b.position.left;j()},g=function(a,b){percent=d/910;c.trigger("sliderDrag",percent);d=b.position.left;j()},h=function(){b&&(window.clearTimeout(b),b=null,e())};(function(){this.$el=$("#slider");a=this.$el.find("#sliderHandle");a.draggable({axis:"x",containment:"parent",start:f,drag:g,stop:h})})()};s=function(a){this.init(a)};s.prototype=new q;GKUtils.extend(s.prototype,{show:function(){var a=this;this.$container.show();setTimeout(function(){a.$container.css("top",a.top)},50)},hide:function(){var a=
this;GKUtils.animate(this.$container,{top:460},function(){a.$container.hide()})},setCenter:function(a,b){var d=this.IMG_DIM;this.el.attr({x:a-d/2,y:b-d/2})},setImageWidth:function(a){this.$container.find("img").css({width:a,height:a});return this},prepareElPosition:function(){var a=2*this.r;this.top=this.rowNum*a;this.left=this.colNum*a;this.setElPosition(this.left+this.r,460+this.r,this.r)},init:function(a){k.getRandomCenter(40);var b=$("<a>"),d=a.pictureUrl||"img/icon_no_photo_80x80.png",e=a.siteStandardProfileRequest?
a.siteStandardProfileRequest.url:"#",c=Math.random()/2+0.5+"s";this.id=a.id;this.profile=a;this.createEl(a.id,40,a.firstName+" "+a.lastName,"cxn");this.$container.css({"-moz-transition-duration":c,"-ms-transition-duration":c,"-o-transition-duration":c,"-webkit-transition-duration":c,"transition-duration":c});b.attr({href:e||"#",title:a.firstName+" "+a.lastName,target:"_new"});b.append($("<img>").addClass("cxn-picture").attr("src",d));this.$circle.append(b)}});r=function(a,b,d,e){this.init(a,b,d,e)};
r.prototype=new q;GKUtils.extend(r.prototype,{calculateCmpyRadius:function(a){return Math.max(100-1E3/(a+10),10)},moveOverlapCircles:function(){return this.moveOverlapCirclesProto.call(this,p)},setEmployees:function(a){var b=this.calculateCmpyRadius(a.length),d=this.cx,e=this.cy;this.employees=a;if(!k.isInBounds(d,e,b))a=k.moveAwayFromEdge(d,e,b),d=a.x,e=a.y,this.move(d,e);this.r!==b&&(this.setRadius(b),this.$label.css({top:b-8+"px",left:b-100+"px"}));return this},resetLabelPosition:function(){var a=
this.el;this.label.attr({x:a.attr("cx"),y:a.attr("cy")-a.attr("r")-5})},doHoverIn:function(){m||(this.$container.addClass("hover"),this.$label.show(),this.moveOverlapCircles())},doHoverOut:function(){this.$container.removeClass("hover");40>this.r&&this.$label.hide()},doClick:function(){!this.wasDragging&&!m&&((l=!l)?(this.highlight(),n=this,m=!0,c.trigger("highlight",{employees:this.employees})):(m=!0,n.unhighlight(),this==n?c.trigger("unhighlight"):(l=!0,this.highlight(),n=this,c.trigger("replaceEmployees",
{employees:this.employees}))));this.wasDragging=!1},doDragStop:function(a,b){this.wasDragging=!0;this.cx=b.position.left+this.r;this.cy=b.position.top+this.r;this.moveOverlapCircles()},highlight:function(){var a=this;this.$label.show();window.setTimeout(function(){a.$container.addClass("highlighted")},h)},unhighlight:function(){this.$container.removeClass("highlighted");GKUtils.fadeOut(f,h)},init:function(a,b,d,e){var c=this.calculateCmpyRadius(b.length),f=k.getRandomCenter(c),g=f.x,f=f.y;this.id=
a;this.origR=c;this.name=d;this.createEl(this.id,c,d,"cmpy").setElPosition(g,f,c);this.$circle.click(this.doClick.bind(this)).hover(this.doHoverIn.bind(this),this.doHoverOut.bind(this));this.$container.addClass(e?"school":"").css("position","absolute").draggable({containment:"parent",stop:this.doDragStop.bind(this)});40<=c&&this.$label.show();this.employees=b;this.pictures=[]}});w=function(){this.init()};w.prototype={$viewport:$("#companies"),add:function(a,b,d,e){a=new r(a,b,d,e);this.renderCompany(a);
return a},renderCompany:function(a){this.$viewport.append(a.getContainer())},showRemainingCompanies:function(a,b,d){var e,c;for(c in a)if(e=a[c])(cmpyCircle=o[c])?cmpyCircle.setEmployees(e).show():(cmpyCircle=this.add(c,a[c],u[c],b),o[c]=cmpyCircle),d.push(cmpyCircle)},renderCompanies:function(a,b){var d;m?this.cmpysToRender={companies:a,schools:b}:(d=[],p.forEach(function(e){var c=a[e.id],f=b[e.id];c?(e.setEmployees(c),d.push(e),a[e.id]=null):f?(e.setEmployees(f),d.push(e),b[e.id]=null):e.hide()}),
this.showRemainingCompanies(a,!1,d),this.showRemainingCompanies(b,!0,d),p=d)},resizeArea:function(){var a=l?200:660,b;l||(b=function(){m=!1;c.trigger("animComplete")});GKUtils.animate(this.$viewport,{height:a+"px"},b);p.forEach(function(a){var b,c;l?(a.origCx=a.cx,a.origCy=a.cy,b=a.cy-a.r,c=a.cx,b=200*(b/660)+a.r,200<=b+a.r&&(b=200-a.r)):(c=a.origCx,b=a.origCy);a.setElPosition(c,b,a.r)})},init:function(){var a=this;this.$el=$("#companies");c.on("highlight",this.resizeArea.bind(this));c.on("unhighlight",
this.resizeArea.bind(this));c.on("animComplete",function(){if(a.cmpysToRender)a.renderCompanies(a.cmpysToRender.companies,a.cmpysToRender.schools),a.cmpysToRender=null})}};ConnectionView=function(){this.init()};ConnectionView.prototype={pictureWidth:80,circles:{},currCxns:[],loadEmployees:function(a,b){var d=b.employees,e=d.length,c,f,g,h,i,x,y;63.96875<e?(this.pictureWidth=Math.floor(9*Math.sqrt(409400/e)/10),this.pictureWidth=Math.max(30,this.pictureWidth)):this.pictureWidth=80;x=Math.floor(890/
this.pictureWidth);y=(d.length-1)/x+1;for(e=0,c=d.length;e<c;++e)f=d[e],f=t[f],g=this.circles[f.id],h=Math.floor(e/x),i=e%x,g||(g=new s(f),this.circles[f.id]=g,this.$el.append(g.getContainer())),g.rowNum=h,g.colNum=i,g.setRadius(this.pictureWidth/2,!1,!1).setImageWidth(this.pictureWidth).prepareElPosition(x,y),this.currCxns.push(g);this.showEmployees();return this},showEmployees:function(){var a=this;this.$wrapper.addClass("show");setTimeout(function(){a.currCxns.forEach(function(a){a.show()})},50);
setTimeout(function(){m=!1;c.trigger("animComplete")},h)},replaceEmployees:function(a,b){var d=this;this.hideEmployees(null,function(){d.loadEmployees(null,b).showEmployees()})},hideEmployees:function(a,b){var d=this;this.currCxns.forEach(function(a){a.hide()});this.currCxns=[];setTimeout(function(){d.$wrapper.removeClass("show");b&&b()},h)},init:function(){this.$el=$("#connections");this.$wrapper=$("#connections-wrapper");c.on("highlight",this.loadEmployees.bind(this));c.on("replaceEmployees",this.replaceEmployees.bind(this));
c.on("unhighlight",this.hideEmployees.bind(this))}};NetworkGraph=function(){this.init()};NetworkGraph.prototype={setCompanies:function(a,b){this.cmpyCollection.renderCompanies(a,b)},setData:function(a){t=a.profiles||null;u=a.cmpyNames||null},init:function(){this.sliderBar=new v;this.cmpyCollection=new w;this.cxnView=new ConnectionView}}})();var onLinkedInLoad;
$(function(){var c,f,h,o=new NetworkGraph,p=(new Date).getTime(),l=$("#date"),m=$("#signin"),n,t,u,v,q,s,r,k,w="Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec".split(","),a=function(a){a=new Date(a);a.setDate(15);a.setHours(0);a.setMinutes(0);a.setSeconds(0);a.setMilliseconds(0);return a},b=function(b,d){var c;n&&t&&(c=a(q+r*d),s=new Date,k.postMessage({allCmpyEmployees:n,allSchoolmates:t,targetDate:c.getTime()}))},d=function(b,d){var c,e;c=a(q+r*d);e=w[c.getMonth()];c=c.getFullYear();l.text(e+" "+
c)},e=function(){var a=GKUtils.getData(c),b=GKUtils.getData(f),d;if(!b||!a)throw"No profile data";b.push(a);h=b;d=new Date;a=new Worker("js/cxnWorker.js");a.addEventListener("message",function(a){if(a.data)n=a.data.companies,t=a.data.schools,u=a.data.cmpyNames,v=a.data.profileObjs,q=a.data.earliestDate,r=p-q,o.setData({profiles:v,cmpyNames:u}),console.log("Processing took "+((new Date).getTime()-d.getTime())+" milliseconds"),GKUtils.fadeIn($("#intro2, #slider, #share"))},!1);a.postMessage({profiles:h})},
j=function(a){$("#yourname").text(a.firstName);setTimeout(function(){GKUtils.fadeIn($("#intro1"))},500)},z=function(a){var b=GKUtils.getData(a);if(b&&b.length)j(b[0]);else throw"Couldn't find your profile!";c=a;f&&e()},g=function(a){f=a;c&&e()},A=function(a){var b=new Date,c;a.data&&(c=a.data.currCompanies||null,currSchools=a.data.currSchools||null);c&&(o.setCompanies(c,currSchools,u),console.log("Processing took "+(b.getTime()-s.getTime())+" milliseconds"))},i=function(){var a="id first-name last-name positions:(start-date,end-date,company:(id,name)) picture-url educations:(school-name,start-date,end-date) site-standard-profile-request:(url)".split(" ");
GKUtils.fadeOut(m,500);setTimeout(function(){GKUtils.fadeIn($("#companies"))},500);$("#viewport").show();IN.API.Profile("me").fields(a).result(z);IN.API.Connections("me").fields(a).result(g)};onLinkedInLoad=function(){GKUtils.fadeIn($("#signin, #title"));IN.Event.on(IN,"auth",i)};(function(){$(window).bind("sliderStop",b);$(window).bind("sliderDrag",d);$(window).bind("sliderStart",function(){GKUtils.fadeOut($(".intro"),500)});k=new Worker("js/snapshotWorker.js");k.addEventListener("message",A,!1)})()});
